# 分词

### 对文本分词

jiebaR提供了四种分词模式，可以通过`worker()`来初始化分词引擎，使用`segment()`进行分词。

```{r}
mixseg = worker()
segment("这是一段测试文本！", mixseg)
mixseg["这是一段测试文本！"]  ### `[]` 为分词符
```

### 设置分行输出

```{r}
mixseg$bylines = TRUE
mixseg[c("这是第一行文本。","这是第二行文本。")]  ### 自动判断输入文件编码模式，默认文件输出在同目录下。
```

### 保留符号

```{r}
mixseg$symbol = TRUE
mixseg$bylines = FALSE
mixseg[c("Hi，这是第一行文本。")]  ### 自动判断输入文件编码模式，默认文件输出在同目录下。
mixseg$symbol = FALSE ### 重设
```

### 添加新词

```{r}
mixseg["这是一个新词"]
new_user_word(mixseg, "这是一个新词", "n")
mixseg["这是一个新词"]
```

### 添加停止词

```{r, include=FALSE}
rm(mixseg)
gc()
```

```{r}
readLines("stop.txt")
mixseg = worker(stop_word = "stop.txt")
new_user_word(mixseg, "停止词", "n")
mixseg["这是一个停止词"]
```

### 对文件进行分词

```{r}
mixseg$output = "output.txt"
head(mixseg["./index.rmd"])  ### 自动判断输入文件编码模式，默认文件输出在同目录下。
```

### 对文件分词，保存文本向量

```{r}
mixseg$write = FALSE ### 不写入把分词结果写入文件
head(mixseg["./index.rmd"])
```

### 设置分行输出

```{r}
mixseg$bylines = TRUE
head(mixseg["./index.rmd"])  ### 自动判断输入文件编码模式，默认文件输出在同目录下。
```

```{r, include=FALSE}
rm(mixseg)
gc()
```
